/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.io.FileReader;
import java.lang.reflect.*;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

import models.User;

public class App {
    /**
     * Greeting application method
     */
    public String getGreeting() {
        return "App for reading JSON file using GSON";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // Define Gson object
        Gson gson = new Gson();

        // Define User object
        User user = new User();

        // Define abstract type for User
        Type listType = new TypeToken<User>() {
        }.getType();

        try {
            // Get absolute path to file
            Path path = Paths.get("data.json");

            // Read json file to java objects
            JsonReader reader = new JsonReader(new FileReader(new File(path.toString())));
            user = gson.fromJson(reader, listType);

            // Show data
            System.out.println(user.toString());
            
        } catch (Exception e) {
            // Catching exception
            e.printStackTrace();
            System.out.println("File doesn't exist");
        }
    }
}
